name: didatikids
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Super Funnel
      fonts: 
        - asset: assets/fonts/Super Funnel.ttf

flutter_launcher_icons:
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_sFundo.png"
  adaptive_icon_foreground: "assets/images/logo_sFundo.png"
  adaptive_icon_background: "#FF673AB7"
  
