# Generated by Django 5.2 on 2025-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAtividades',
            fields=[
                ('id_atividade', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_atividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbAvatares',
            fields=[
                ('id_avatar', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('caminho', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tb_avatares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCriancaAtividades',
            fields=[
                ('pk', models.CompositePrimaryKey('id_atividade', 'id_crianca', blank=True, editable=False, primary_key=True, serialize=False)),
                ('desempenho', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_crianca_atividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCriancaAvatares',
            fields=[
                ('pk', models.CompositePrimaryKey('id_avatar', 'id_crianca', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_crianca_avatares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCriancas',
            fields=[
                ('id_crianca', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('tempo_tela', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_criancas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCriancaTopicos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_topico', 'id_crianca', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_crianca_topicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDificuldades',
            fields=[
                ('id_dificuldade', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dificuldades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbFaixasetarias',
            fields=[
                ('id_faixa_etaria', models.IntegerField(primary_key=True, serialize=False)),
                ('faixa_etaria', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tb_faixasetarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbResponsaveis',
            fields=[
                ('id_responsavel', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_responsaveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbTopicos',
            fields=[
                ('id_topico', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_topicos',
                'managed': False,
            },
        ),
    ]
